### ISSUE TITLE
Day08. 回溯算法解决岛屿题目

### ISSUE THREAD

**Issue by labuladong** [labuladong/advanced-challenge#11]
今日学习文章：[回溯算法解决岛屿题目](https://labuladong.github.io/article/fname.html?fname=岛屿题目)

请于两天内在本 issue 下评论完成打卡，学习过程中如果遇到无法解决的问题可以在群里交流。

**Comment by tanlandy** [comment]
Python, using visited set only, no flood
[200](https://leetcode.com/problems/number-of-islands/discuss/2048566/Python-BFS-DFS-with-time-and-space-analysis)
[1254](https://leetcode.com/problems/number-of-closed-islands/discuss/2048615/Python-DFS)
[1020](https://leetcode.com/problems/number-of-enclaves/discuss/2048638/Python-DFS)
[695](https://leetcode.com/problems/max-area-of-island/discuss/2048665/Python-DFS)
[1905](https://leetcode.com/problems/count-sub-islands/discuss/2048685/Python-DFS)
[694](https://leetcode.com/problems/number-of-distinct-islands/discuss/2048736/Python-DFS-using-set)

**Comment by XINGXINGFIONA** [comment]
https://leetcode.com/problems/number-of-distinct-islands/discuss/2048950/dfs

**Comment by ldai1** [comment]
https://leetcode.com/problems/number-of-islands/discuss/2049107/JAVA-DFS

**Comment by taihui** [comment]
https://leetcode.com/problems/number-of-islands/discuss/2049196/Python-3-DFS

https://leetcode.com/problems/number-of-closed-islands/discuss/2049229/Python-3-DFS

**Comment by minnownino** [comment]
https://leetcode.cn/problems/number-of-islands/solution/by-minnownino-6j6a/

**Comment by huanlaikuxiduan** [comment]
https://leetcode.cn/problems/count-sub-islands/solution/dao-yu-wen-ti-by-huan-lai-ku-xi-duan-3nbx/

**Comment by davidditao** [comment]
https://leetcode.cn/problems/number-of-islands/solution/by-pedantic-mcleanbpp-xadr/

**Comment by LFool** [comment]
https://leetcode.cn/problems/number-of-islands/solution/by-lfool-2wmw/

**Comment by azelee** [comment]
cpp

- [200. 岛屿数量](https://leetcode-cn.com/problems/number-of-islands/)
https://leetcode.cn/problems/number-of-islands/solution/by-li-jinze-r6w6/

- [1254. 统计封闭岛屿的数目](https://leetcode.cn/problems/number-of-closed-islands/)
https://leetcode.cn/problems/number-of-closed-islands/solution/by-li-jinze-yr8s/

- [1020. 飞地的数量](https://leetcode.cn/problems/number-of-enclaves/)
https://leetcode.cn/problems/number-of-enclaves/solution/by-li-jinze-dnhr/

- [695. 岛屿的最大面积](https://leetcode.cn/problems/max-area-of-island/)
https://leetcode.cn/problems/max-area-of-island/solution/by-li-jinze-sd0a/

- [1905. 统计子岛屿](https://leetcode.cn/problems/count-sub-islands/)
https://leetcode.cn/problems/count-sub-islands/solution/by-li-jinze-ylup/

- [694. 不同岛屿的数量](https://leetcode.cn/problems/number-of-distinct-islands/)
- https://leetcode.cn/problems/number-of-distinct-islands/solution/by-li-jinze-k2f4/

**Comment by azelee** [comment]
cpp

- [200. 岛屿数量](https://leetcode-cn.com/problems/number-of-islands/)
https://leetcode.cn/problems/number-of-islands/solution/by-li-jinze-r6w6/

- [1254. 统计封闭岛屿的数目](https://leetcode.cn/problems/number-of-closed-islands/)
https://leetcode.cn/problems/number-of-closed-islands/solution/by-li-jinze-yr8s/

- [1020. 飞地的数量](https://leetcode.cn/problems/number-of-enclaves/)
https://leetcode.cn/problems/number-of-enclaves/solution/by-li-jinze-dnhr/

- [695. 岛屿的最大面积](https://leetcode.cn/problems/max-area-of-island/)
https://leetcode.cn/problems/max-area-of-island/solution/by-li-jinze-sd0a/

- [1905. 统计子岛屿](https://leetcode.cn/problems/count-sub-islands/)
https://leetcode.cn/problems/count-sub-islands/solution/by-li-jinze-ylup/

- [694. 不同岛屿的数量](https://leetcode.cn/problems/number-of-distinct-islands/)
https://leetcode.cn/problems/number-of-distinct-islands/solution/by-li-jinze-k2f4/

**Comment by brucecat** [comment]
https://leetcode.cn/problems/number-of-islands/solution/by-scuhzs-qw1w/

**Comment by zhanglei-underdog** [comment]
https://leetcode.cn/problems/number-of-distinct-islands/solution/bu-tong-de-dao-yu-shu-liang-by-vrikxgwzl-xwrn/

**Comment by Sukey925** [comment]
https://leetcode.cn/problems/number-of-islands/solution/by-sukey-f-nnhz/

**Comment by GithubMingEnter** [comment]
C++:https://leetcode.cn/problems/count-sub-islands/solution/tong-ji-zi-dao-yu-by-kou-ming-2aoh/

**Comment by Merlin218** [comment]
https://leetcode.cn/problems/number-of-islands/solution/by-merlin218-q265/

**Comment by 1061961387** [comment]
695：https://leetcode.cn/problems/count-sub-islands/solution/by-lattr-4-1ypg/

**Comment by Goolloo** [comment]
- https://leetcode.com/problems/number-of-islands/discuss/2050266/Java-DP-DFS-all-track-flip-target-to-another-value
- https://leetcode.com/problems/number-of-closed-islands/discuss/2050351/Java-DP-DFS-change-all-island-on-edge-first
- https://leetcode.com/problems/number-of-enclaves/discuss/2050364/Java-DP-DFS-flip-all-islands-on-edge-first
- https://leetcode.com/problems/max-area-of-island/discuss/2050377/Java-DP-DFS-count-and-flip-each-island
- https://leetcode.com/problems/count-sub-islands/discuss/2050401/Java-DP-DFS-compare-and-flip-cells
- https://leetcode.com/problems/number-of-distinct-islands/discuss/2050458/Java-DP-DFS-flip-and-record-each-move-start-and-end

**Comment by YuYaoMao** [comment]
https://leetcode.cn/problems/number-of-islands/solution/c-by-yuyaomao-a9rs/

**Comment by Anzeanan** [comment]
https://leetcode.cn/problems/number-of-islands/solution/labuladongda-qia-tiao-zhan-0511-0525_051-0r32/

**Comment by NealCou** [comment]
200. 岛屿的数量 https://leetcode.cn/problems/number-of-islands/solution/-by-nealcou-m68r/

**Comment by clockssss** [comment]
1905 https://leetcode.cn/problems/count-sub-islands/solution/by-long-5eu-x9dq/
200 https://leetcode.cn/problems/number-of-islands/solution/by-long-5eu-klf2/

**Comment by SamsonJy** [comment]
200: https://leetcode.com/problems/number-of-islands/discuss/2050864/Java-dfs

**Comment by YourRaymond** [comment]
https://leetcode.cn/problems/max-area-of-island/solution/by-lming-9-f88v/

**Comment by minixx** [comment]
https://leetcode.cn/problems/number-of-islands/solution/-by-moonno-397f/

**Comment by fzfzlfz** [comment]
[200. 岛屿数量](https://leetcode.cn/problems/number-of-islands/)
https://leetcode.cn/problems/number-of-islands/solution/by-yi-mo-shao-nu-5v6h/

**Comment by FanWangRIT** [comment]
https://leetcode.cn/problems/number-of-closed-islands/solution/by-fan-wang-7-rx44/

**Comment by Carlotte-yi** [comment]
https://leetcode.cn/problems/number-of-islands/solution/by-xiyou_peng_yu_yan-adtr/

**Comment by gutouyu** [comment]
200 https://leetcode.cn/problems/number-of-islands/solution/by-ningleexx-giut/  dfs遇到陆地就填海

**Comment by No-Sky** [comment]
https://leetcode.cn/problems/number-of-islands/solution/dao-by-no-sky-apfe/
https://leetcode.cn/problems/number-of-closed-islands/solution/tong-ji-feng-bi-dao-yu-de-shu-mu-by-no-s-t5d9/
https://leetcode.cn/problems/number-of-enclaves/solution/by-no-sky-9ra4/
https://leetcode.cn/problems/max-area-of-island/solution/dao-yu-de-zui-da-mian-ji-by-no-sky-alfv/

**Comment by yaheiheio** [comment]
https://leetcode.cn/problems/number-of-islands/solution/hui-su-suan-fa-by-csseudaeaq-9mda/

**Comment by SmartDengC** [comment]
https://leetcode.cn/problems/number-of-islands/solution/by-smartdengc-9q2i/

**Comment by Khannoob** [comment]
https://leetcode.cn/problems/number-of-islands/solution/dfs-by-unruffled-driscoll51z-gkbm/
https://leetcode.cn/problems/number-of-enclaves/solution/dfsfeidi-by-unruffled-driscoll51z-ygzl/

**Comment by fanfeiyangcn** [comment]
https://leetcode.cn/problems/number-of-islands/solution/by-wu-jin-wei-lan-b-bqmp/

**Comment by JiangCheng-2021** [comment]
https://leetcode.cn/problems/count-sub-islands/solution/by-jiangcheng-2021-dihp/

**Comment by Annannay** [comment]
https://leetcode.cn/problems/number-of-islands/solution/dao-yu-shu-liang-by-annanna-zbx9/

**Comment by rzhao29** [comment]
https://leetcode.com/problems/number-of-islands/discuss/2052341/Flood

**Comment by annalovecode** [comment]
https://leetcode.cn/problems/max-area-of-island/solution/dfs-by-annalovecode-4264/

**Comment by goldenlimit** [comment]
Python3:
[200. Number of Islands](https://leetcode.cn/problems/number-of-islands/)
https://leetcode.cn/problems/number-of-islands/solution/by-goldenlimit-gt9c/

**Comment by strin-sr** [comment]
https://leetcode.cn/problems/max-area-of-island/solution/by-youyou-ui-1vbf/
https://leetcode.cn/problems/number-of-enclaves/solution/by-youyou-ui-ugpz/
https://leetcode.cn/problems/number-of-closed-islands/solution/by-youyou-ui-g950/
https://leetcode.cn/problems/number-of-islands/solution/df-by-youyou-ui-dnkd/

**Comment by sfj666** [comment]
https://leetcode.com/problems/number-of-islands/discuss/2052926/Number-of-Islands-python3

**Comment by dreamer2q** [comment]
https://leetcode.cn/problems/number-of-islands/solution/dfs-bian-li-by-dm2q-3sjj/

**Comment by tarian1995** [comment]
- 1254 : https://leetcode.cn/problems/number-of-closed-islands/solution/dfs-by-tab-o-w2lr/
- 695: https://leetcode.cn/problems/max-area-of-island/solution/dfs-by-tab-o-ybfe/

**Comment by bthylaz** [comment]
https://leetcode.cn/problems/number-of-islands/solution/200-dao-yu-shu-liang-by-bthyla-ec02/
https://leetcode.cn/problems/number-of-closed-islands/solution/1254-tong-ji-feng-bi-dao-yu-de-shu-mu-by-czty/

**Comment by wangzhanxd** [comment]
https://leetcode.com/problems/number-of-islands/discuss/2053937/python3-dfs

**Comment by sphk123456** [comment]
Q200：https://leetcode.cn/problems/number-of-islands/solution/by-wan-70-l8g8/

**Comment by AmyIsMin** [comment]
https://leetcode.cn/problems/number-of-islands/solution/by-yxian-sheng-7-xm9p/

**Comment by liu-hantong** [comment]
https://leetcode.com/problems/number-of-islands/discuss/2054119/Python-DFS-Solution-Explained

**Comment by xiaolou123** [comment]
https://leetcode.cn/problems/number-of-islands/solution/by-remtimes-t3uv/

**Comment by ZLZhangLi** [comment]
https://leetcode.cn/problems/number-of-islands/solution/python-daoyushuliang-by-zlzhangli-524m/

**Comment by bright1109** [comment]
https://leetcode.cn/problems/number-of-islands/solution/c-by-tina_huskie-x76a/

**Comment by BMYzm** [comment]
https://leetcode.cn/problems/count-sub-islands/solution/dfs-by-bmy-6trn/

**Comment by LetmeTryagain** [comment]
200: https://leetcode.cn/problems/number-of-islands/solution/dao-yu-shu-liang-by-4iovekwz80-dxwe/

**Comment by acse-yw3821** [comment]
https://leetcode.cn/problems/number-of-closed-islands/solution/java-dfs-by-yann-w-221e/

**Comment by JiejieZhao** [comment]
https://leetcode.cn/problems/number-of-islands/solution/200dao-yu-shu-liang-by-serendipityj-131x/

**Comment by YaokunLee** [comment]
https://leetcode.cn/problems/number-of-islands/solution/by-qing-niao-1111-ewkr/

**Comment by kf953741** [comment]
https://leetcode.cn/problems/number-of-islands/solution/c-dfs-by-kf953741-mkte/

**Comment by geekvc** [comment]
https://leetcode.cn/problems/number-of-islands/solution/dao-yu-ge-shu-by-geekvc-t-20f6/

**Comment by ZiqiSun** [comment]
https://leetcode.com/problems/number-of-islands/discuss/2054333/java-dfs

**Comment by shmily101** [comment]
https://leetcode.cn/problems/count-sub-islands/solution/javascript-by-mikeythief-fhj1/

**Comment by damondenghj** [comment]
https://leetcode.cn/problems/number-of-islands/solution/by-6oofy-turingj5y-l4oy/

**Comment by Han1015** [comment]
https://leetcode.com/problems/max-area-of-island/discuss/2072335/js

**Comment by zhzeshu** [comment]
https://leetcode.com/problems/count-sub-islands/discuss/2073231/python-DFS

**Comment by eryao** [comment]
https://leetcode.com/problems/number-of-islands/discuss/2075210/Copied-Solution

**Comment by mapstory6788** [comment]
https://leetcode.cn/problems/number-of-islands/solution/by-yi-ci-guo-e4u1/

**Comment by zhou-yan-hua** [comment]
https://leetcode.cn/problems/number-of-islands/solution/by-hua-sk-0evj/

**Comment by YangChenyuShawn** [comment]
https://leetcode.cn/problems/number-of-islands/solution/dao-yu-shu-liang-by-sui-ji-guo-cheng-sui-7fc6/

**Comment by youngerzjc** [comment]
https://leetcode.cn/problems/number-of-islands/solution/dao-yu-lian-xi-by-yao-shi-6fvm/

**Comment by whyyue** [comment]
200.岛屿数量 https://leetcode.cn/problems/number-of-islands/solution/day8-by-estherstarry-6d5o/

**Comment by weic6** [comment]
https://leetcode.cn/problems/number-of-islands/solution/by-weigiegie-fquc/

**Comment by y-start** [comment]
https://leetcode.cn/problems/max-area-of-island/solution/by-abc_cba-q9tl/

**Comment by SteveSun12138** [comment]
https://leetcode.com/problems/number-of-islands/discuss/2077948/Steve's-Java-Solution
